Const batch 100
Const threads 4
Const log CIFAR_002.log
Data D1 filename ../DataSet/training binary
Data D2 filename ../DataSet/test binary
Network N1
data tr D1
data ts D2
layer in CI 5 nz 3 nr 32 nc 32 cr 32 cc 32
layer c0 C 6 nk 16 kr 3 kc 3 rpad 0 cpad 0 stride 1
layer p0 MP 2 sizer 2 sizec 2
layer c1 C 6 nk 32 kr 3 kc 3 rpad 0 cpad 0 stride 1
layer p1 MP 2 sizer 2 sizec 2
layer c2 C 6 nk 64 kr 3 kc 3 rpad 0 cpad 0 stride 1
layer p2 MP 2 sizer 2 sizec 2
layer fc1 F 1 numnodes 1024
layer fc2 F 1 numnodes 512
layer fo FO 2 criterion classification autoencoder 0
link N1 in N1 c0
link N1 c0 N1 p0
link N1 p0 N1 c1
link N1 c1 N1 p1
link N1 p1 N1 c2
link N1 c2 N1 p2
layer fr R 2 prevlayer N1 p2 local 0
link N1 fr N1 fc1
link N1 fc1 N1 fc2
link N1 fc2 N1 fo
END_Network
command D1 zscore 0
command D2 zscore 1 D1
amendment N1 * bn 1
amendment N1 fc1 drop 0.500000
amendment N1 fc2 drop 0.500000
amendment N1 in noiser 0.500000
amendment N1 in noisesd 1.000000
amendment N1 * mu 0.010000
command N1 train 1 nepoch 30
amendment N1 * mu 0.005000
command N1 train 1 nepoch 30
amendment N1 * mu 0.002500
command N1 train 1 nepoch 30
END
